name: kaggle_dagster_dbt_snowflake_poc
version: 1.0.0
profile: kaggle_dagster_dbt_snowflake_poc

models:
  kaggle_dagster_dbt_snowflake_poc:
    staging:
      +schema: STAGING
    intermediate:
      +schema: INTERMEDIATE
    marts:
      +schema: MARTS
